export type OverlayConfig = {
  overlayEnabled: boolean;
  overlayLogoPath: string;
  overlayLogoPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  overlayLogoScale: number;
  overlayLogoAnimation: "none" | "pulse" | "breathe" | "fade-in" | "flash";
  overlayChannelName: string;
  overlayHeadline: string;
  overlayTickerText: string;
  overlayBannerColor: string;
  overlayTickerColor: string;
  overlayTickerSpeed: number;
  overlayLiveCount: boolean;
  youtubeChannelId: string;
  overlayQrEnabled: boolean;
  overlayQrUrl: string;
  overlayQrLabel: string;
  overlayQrPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  overlayQrSize: "small" | "medium" | "large";
  overlaySocialEnabled: boolean;
  overlaySocialHandle: string;
  lowerThirdStyle: "none" | "l-cut" | "breaking-news" | "ticker-name" | "side-strip";
  lowerThirdName: string;
  lowerThirdTitle: string;
  lowerThirdAccentColor: string;
  lowerThirdAnimation: "none" | "slide-wipe" | "scale-up" | "fade" | "drop-in";
  tickerStyle: "crawl" | "flipper" | "flash-alert";
  messageEnabled: boolean;
  messageText: string;
  messageStyle: "news-classic" | "breaking-alert" | "minimal-clean" | "cinema" | "social-card" | "broadcast-official" | "pill" | "watermark";
  messagePosition: "top-left" | "top-right" | "center" | "bottom-left" | "bottom-right" | "bottom-center";
  subBoxEnabled: boolean;
  subBoxStyle: "minimal" | "card" | "broadcast" | "flip-counter" | "whatsapp" | "recent-activity" | "neon-glow" | "glass-card" | "scoreboard" | "pill-badge";
  subBoxPosition: "top-left" | "top-right" | "center-left" | "center-right" | "bottom-left" | "bottom-right";
  subBoxShowViewers: boolean;
  subBoxAnimStyle: "none" | "count-up" | "pulse-glow" | "slide-in" | "celebrate";
  chatEnabled: boolean;
  chatPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  chatStyle: "bubble" | "list";
  chatMaxMessages: number;
  viewerLayout: "standard" | "pip-br" | "pip-bl" | "pip-tr" | "split-v" | "split-h" | "cinema" | "fullscreen" | "l-shape";
  viewerScreenScale: number;
  viewerScreenX: number;
  viewerScreenY: number;
  adEnabled: boolean;
  adStyle: "sponsor-banner" | "lower-ad" | "corner-bug" | "countdown-card" | "product-card" | "ribbon";
  adText: string;
  adSubText: string;
  adBgColor: string;
  adAccentColor: string;
  adPosition: "top-left" | "top-right" | "center" | "bottom-left" | "bottom-right" | "bottom-center";
  adCtaLabel: string;
  adCountdown: number;
};

export type StreamConfig = OverlayConfig & {
  id: string;
  sourceType: "tiktok" | "youtube" | "camera";
  tiktokUsername: string;
  youtubeSourceUrl: string;
  cameraDevice: string;
  youtubeStreamKey: string;
  facebookRtmpUrl: string;
  ratio: "mobile" | "desktop";
  quality: "best" | "720p" | "480p";
  fps: "20" | "25" | "30";
  muted: boolean;
  autoRestart: boolean;
  status: "idle" | "streaming" | "error" | "reconnecting";
};

export type InsertStream = Omit<StreamConfig, "id" | "status">;
