export type OverlayConfig = {
  overlayEnabled: boolean;
  overlayLogoPath: string;
  overlayLogoPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  overlayLogoScale: number;
  overlayLogoAnimation: "none" | "pulse" | "breathe" | "fade-in" | "flash";
  overlayChannelName: string;
  overlayHeadline: string;
  overlayTickerText: string;
  overlayBannerColor: string;
  overlayTickerColor: string;
  overlayTickerSpeed: number;
  overlayLiveCount: boolean;
  youtubeChannelId: string;
  overlayQrEnabled: boolean;
  overlayQrUrl: string;
  overlayQrLabel: string;
  overlayQrPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  overlayQrSize: "small" | "medium" | "large";
  overlaySocialEnabled: boolean;
  overlaySocialHandle: string;
  lowerThirdStyle: "none" | "l-cut" | "breaking-news";
  lowerThirdName: string;
  lowerThirdTitle: string;
  lowerThirdAccentColor: string;
  lowerThirdAnimation: "none" | "slide-wipe" | "scale-up";
  tickerStyle: "crawl" | "flipper";
  messageEnabled: boolean;
  messageText: string;
  messageStyle: "news-classic" | "breaking-alert" | "minimal-clean" | "cinema" | "social-card" | "broadcast-official";
  messagePosition: "top-left" | "top-right" | "center" | "bottom-left" | "bottom-right" | "bottom-center";
  subBoxEnabled: boolean;
  subBoxStyle: "minimal" | "card" | "broadcast" | "flip-counter" | "whatsapp" | "recent-activity";
  subBoxPosition: "top-left" | "top-right" | "center-left" | "center-right" | "bottom-left" | "bottom-right";
  subBoxShowViewers: boolean;
  chatEnabled: boolean;
  chatPosition: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  chatStyle: "bubble" | "list";
  chatMaxMessages: number;
};

export type StreamConfig = OverlayConfig & {
  id: string;
  sourceType: "tiktok" | "youtube" | "camera";
  tiktokUsername: string;
  youtubeSourceUrl: string;
  cameraDevice: string;
  youtubeStreamKey: string;
  facebookRtmpUrl: string;
  ratio: "mobile" | "desktop";
  quality: "best" | "720p" | "480p";
  fps: "20" | "25" | "30";
  muted: boolean;
  autoRestart: boolean;
  status: "idle" | "streaming" | "error" | "reconnecting";
};

export type InsertStream = Omit<StreamConfig, "id" | "status">;
